---

- name: Creating Service File | Rethink
  template:
    src: service.j2
    dest: /usr/lib/systemd/system/rethink.service

- name: Starting rethink Service
  systemd:
    name: rethink
    state: started
    enabled: true
    daemon_reload: true