
- hosts: rthinkdb-hosts
  gather_facts: true
  tasks:
    - name: Getting Vars from | Vars/{{ rethinkClusterMode }}
      include_vars: "vars/{{ rethinkClusterMode }}.yml"

- hosts: rthinkdb-hosts
  gather_facts: true
  roles:
    - common
    - service

