- hosts: rthinkdb-hosts
  gather_facts: true
  roles:
    - common
  tasks:
    - name: Ensuring RthinkDB is Running
      systemd:
        name: rthinkdb
        state: started
        enabled: True
        daemon_reload: True
